CLUSTER_PLAN: dev
NAMESPACE: default
CLUSTER_NAME: dpaul-tce-guest
CNI: antrea
CONTROL_PLANE_MACHINE_TYPE: t3.small
NODE_MACHINE_TYPE: t3.large
CONTROL_PLANE_MACHINE_COUNT: 1
WORKER_MACHINE_COUNT: 3
AWS_REGION: eu-west-1
AWS_NODE_AZ: eu-west-1a
AWS_SSH_KEY_NAME: dpaul-key
AWS_PRIVATE_NODE_CIDR: 172.30.2.0/24
AWS_PRIVATE_SUBNET_ID: subnet-0c6797b4a4081fb28
AWS_PUBLIC_NODE_CIDR: 172.30.1.0/24
AWS_PUBLIC_SUBNET_ID: subnet-0957b77c8a8c1e2c3
AWS_VPC_CIDR: 172.30.0.0/16
AWS_VPC_ID: vpc-00a111c40a1c7b86f
BASTION_HOST_ENABLED: false
ENABLE_MHC: true
MHC_UNKNOWN_STATUS_TIMEOUT: 5m
MHC_FALSE_STATUS_TIMEOUT: 12m
ENABLE_AUDIT_LOGGING: false
ENABLE_DEFAULT_STORAGE_CLASS: true
CLUSTER_CIDR: 100.96.0.0/11
SERVICE_CIDR: 100.64.0.0/13
ENABLE_AUTOSCALER: false
ENABLE_CEIP_PARTICIPATION: "false"
INFRASTRUCTURE_PROVIDER: aws
OS_ARCH: amd64
OS_NAME: amazon
OS_VERSION: "2"
AWS_SECURITY_GROUP_BASTION: sg-0f6ae4ba2888efe69
AWS_SECURITY_GROUP_NODE: sg-0f978fa48f762d233
AWS_SECURITY_GROUP_CONTROLPLANE: sg-0a1bed4f2e2f7aad5
AWS_SECURITY_GROUP_APISERVER_LB: sg-08207b7f2bcb527b5